name: Validate & Release

on: push

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: semantic-release
        if: github.ref == 'refs/heads/develop'
        id: semantic
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test output
        run: |
          echo "$OUTPUTS"
          echo "$NEW_RELEASE_PUBLISHED"
          echo "$RELEASE_MAJOR"
          echo "$RELEASE_MINOR"
          echo "$RELEASE_PATCH"
        env:
          OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
